version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 908756929947.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - ls 
      - docker build -t usdjpybot .
      - docker tag usdjpybot:latest 908756929947.dkr.ecr.ap-southeast-1.amazonaws.com/usdjpybot:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push usdjpybot:latest 908756929947.dkr.ecr.ap-southeast-1.amazonaws.com/usdjpybot
      - echo Creating imagedefinitions.json file...
      - echo '[{"name":"usdjpybot","imageUri":"usdjpybot:latest 908756929947.dkr.ecr.ap-southeast-1.amazonaws.com/usdjpybot"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
